# Generated by Django 5.2 on 2025-04-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, help_text='页面URL', max_length=2048, unique=True)),
                ('content', models.TextField(help_text='页面原始内容')),
                ('clean_content', models.TextField(blank=True, help_text='清洗后的Markdown内容', null=True)),
                ('status_code', models.IntegerField(default=200, help_text='HTTP状态码')),
                ('headers', models.JSONField(default=dict, help_text='HTTP响应头')),
                ('timestamp', models.BigIntegerField(help_text='爬取时间戳')),
                ('links', models.JSONField(default=list, help_text='页面中提取的链接列表')),
                ('mimetype', models.CharField(help_text='内容MIME类型', max_length=255)),
                ('title', models.CharField(blank=True, help_text='页面标题', max_length=1024, null=True)),
                ('description', models.TextField(blank=True, help_text='页面描述', null=True)),
                ('keywords', models.TextField(blank=True, help_text='关键词', null=True)),
                ('source', models.CharField(help_text='域名来源', max_length=255)),
                ('metadata', models.JSONField(default=dict, help_text='其他元数据')),
                ('content_hash', models.CharField(db_index=True, help_text='内容哈希值，用于去重和变更检测', max_length=64)),
                ('crawler_id', models.CharField(help_text='爬虫ID', max_length=255)),
                ('crawler_type', models.CharField(help_text='爬虫类型', max_length=50)),
                ('crawler_config', models.JSONField(default=dict, help_text='爬虫配置')),
                ('site_id', models.CharField(db_index=True, help_text='站点ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('version', models.IntegerField(default=1, help_text='版本号')),
                ('index_operation', models.CharField(choices=[('new', '新增'), ('edit', '更新'), ('delete', '删除')], default='new', help_text='索引操作类型', max_length=10)),
                ('is_indexed', models.BooleanField(default=False, help_text='是否已索引')),
            ],
            options={
                'db_table': 'sitesearch_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='sitesearch__content_cba961_idx'), models.Index(fields=['site_id'], name='sitesearch__site_id_dec2da_idx'), models.Index(fields=['created_at'], name='sitesearch__created_118540_idx'), models.Index(fields=['is_indexed'], name='sitesearch__is_inde_3d7ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawlHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, help_text='内容哈希值', max_length=64)),
                ('url', models.URLField(db_index=True, help_text='页面URL', max_length=2048)),
                ('timestamp', models.BigIntegerField(help_text='爬取时间戳')),
                ('version', models.IntegerField(help_text='版本号')),
                ('change_type', models.CharField(choices=[('new', '新增'), ('edit', '更新'), ('delete', '删除')], help_text='变更类型', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('metadata', models.JSONField(default=dict, help_text='变更元数据')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sitesearch_storage.document')),
            ],
            options={
                'db_table': 'sitesearch_crawl_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='sitesearch__content_040f12_idx'), models.Index(fields=['url'], name='sitesearch__url_882e1c_idx'), models.Index(fields=['created_at'], name='sitesearch__created_c0517f_idx')],
            },
        ),
    ]
