# Generated by Django 5.2 on 2025-04-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesearch_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, help_text='站点ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'db_table': 'sitesearch_site_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='sitesearch__site_id_dec2da_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='site_id',
        ),
        migrations.AddField(
            model_name='sitedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sitesearch_storage.document'),
        ),
        migrations.AddIndex(
            model_name='sitedocument',
            index=models.Index(fields=['site_id'], name='sitesearch__site_id_7f35d6_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedocument',
            index=models.Index(fields=['created_at'], name='sitesearch__created_3402ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitedocument',
            unique_together={('site_id', 'document')},
        ),
    ]
