apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  namespace: sitesearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: sitesearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.4.23
        ports:
        - containerPort: 19530
        - containerPort: 9091
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: sitesearch-config
              key: ETCD_ENDPOINTS
        - name: MINIO_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: sitesearch-config
              key: MINIO_ADDRESS
        command:
        - milvus
        args:
        - run
        - standalone
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - name: milvus-storage
          mountPath: /var/lib/milvus
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: milvus-storage
        persistentVolumeClaim:
          claimName: milvus-pvc
      initContainers:
      - name: wait-for-etcd
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z etcd 2379; do
            echo "Waiting for etcd..."
            sleep 2
          done
      - name: wait-for-minio
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          until nc -z minio 9000; do
            echo "Waiting for minio..."
            sleep 2
          done
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: sitesearch
spec:
  selector:
    app: milvus
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
  - name: http
    port: 9091
    targetPort: 9091
  type: ClusterIP 