name: Build Backend Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - ".github/workflows/docker-build.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: sitesearch
  OWNER: betterandbetterii

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Docker image tag
        id: generate_tag
        run: |
          TAG=$(date +%Y%m%d-%H%M)
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.SERVICE_NAME }}:${{ env.TAG }},${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.SERVICE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.SERVICE_NAME }}:buildcache,mode=max
